project:
  type: website
  output-dir: docs

website:
  title: "José Bampi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

