---
title: "Publications"
---

## Papers

1.  **Bampi JVB**, Arcanjo GGA, Santos KM, Ventura MS, Lemos EF, Clark RA, Thomas KA, White RG, Croda J. Acceptability of a proposed new tuberculosis vaccine among people deprived of liberty in Brazil. Vaccine. 2026 Apr 19;79:128492. doi: [10.1016/j.vaccine.2026.128492](https://www.sciencedirect.com/science/article/pii/S0264410X26003002)

2.  **Bampi JVB**, Noguera SV, Santos SAD, Marchi AP, Côrtes MF, Fonseca JVDS, Santos ILD, Rossi F, Bazzo ML, Hughes G, Borges I, Costa SF. Genotypic virulence profiles and mobile genetic elements related to invasiveness in Neisseria gonorrhoeae strains. Rev Inst Med Trop Sao Paulo. 2026 Mar 13;68:e25. doi: [10.1590/S1678-9946202668025](https://pmc.ncbi.nlm.nih.gov/articles/PMC12987606/)

3.  Jung E, **Bampi JVB**, Moura da Silva A, Liu YE, Tsuha DH, Salindri AD, da Silva Santos A, de Oliveira RD, Croda J, Andrews JR. Longitudinal symptom transitions predict incident tuberculosis risk in serial active case finding. J Infect Dis. 2026 Feb 21:jiag119. doi: [10.1093/infdis/jiag119](https://academic.oup.com/jid/advance-article/doi/10.1093/infdis/jiag119/8493258)

4.  McCreesh N, MacPherson P, **Bampi JVB**, Engel N, Kranzer K, Khan PY. Reported Tuberculosis Symptoms: An Inadequate Classifier of Disease State. Clin Infect Dis. 2026 Mar 17;82(3):e589-e594. doi: [10.1093/cid/ciaf611](https://academic.oup.com/cid/article/82/3/e589/8374620?searchresult=1)

5.  Salindri, A.D., **Bampi, J.V.B.**, Busatto, C. *et al.* Evaluation of an ultra-portable X-ray system with automated interpretation for tuberculosis active case finding in carceral settings: a diagnostic test accuracy study. BMC Infect Dis 2025, 1480. doi: [10.1186/s12879-025-11835-0](https://bmcinfectdis.biomedcentral.com/articles/10.1186/s12879-025-11835-0)

6.  Mabene Y, **Bortolotto Bampi JV**, Lemos EF, de Oliveira R, Gonçalves C, Delgado Alves ML, Coutinho Echevarria M, Croda J, Andrews JR, Liu YE. Tuberculosis treatment outcomes after transfer or release from incarceration: a retrospective cohort study from Brazil. BMC Glob Public Health. 2025 Oct 21;3(1):93. doi: [10.1186/s44263-025-00210-5.](https://bmcglobalpublichealth.biomedcentral.com/articles/10.1186/s44263-025-00210-5)

7.  Gonçalves LA, Anjos BB, Tavares BM, Marchi AP, Côrtes MF, Higashino HR, de Carvalho Moraes BDG, **Bampi JVB**, Pinheiro LD, Spadao FS, Rocha V, Guimarães T, Costa SF. Colonization by Extended-Spectrum β-Lactamase-Producing Enterobacterales and Bacteremia in Hematopoietic Stem Cell Transplant Recipients. Antibiotics (Basel). 2024 May 15;13(5):448. doi: [10.3390/antibiotics13050448.](https://www.mdpi.com/2079-6382/13/5/448)

8.  de Oliveira VF, Coracini Tonacio A, Marchi AP, Farrel Côrtes M, Luiza Bazzo M, Takeshigue Lemos G, **Bortolotto Bampi JV**, Patricia Sanchez Espinoza E, Luiz Tarsia Duarte E, Cristina Ruedas Martins R, Alves Dos Santos S, Vieira Perdigão Neto L, Ramalho da Costa-Lourenço AP, Regina Bonelli R, Rita Elmore M, Rossi F, Hughes G, Figueiredo Costa S. Neisseria gonorrhoeae arthritis in a patient with systemic lupus: resistance and virulence profiles. Microbes Infect. 2023 Jan-Feb;25(1-2):105037. doi: [10.1016/j.micinf.2022.105037.](https://www.sciencedirect.com/science/article/pii/S1286457922001071?via%3Dihub)

9.  **Bampi JVB**, Correa ME, Bet GMDS, Marchioro SB, Simionatto S. Descriptive analysis of syphilis cases reported in Mato Grosso do Sul, Brazil identifies failure in treatment. Rev Soc Bras Med Trop. 2019 Apr 25;52:e20180026. doi: [10.1590/0037-8682-0026-2018.](https://www.scielo.br/j/rsbmt/a/mDVg7qZpGyfpgGFM3XCqQ6g/?lang=en)

10. Maciel WG, da Silva KE, Croda J, Cayô R, Ramos AC, de Sales RO, de Almeida de Souza GH, **Bampi JVB**, Limiere LC, Casagrande JC, Gales AC, Simionatto S. Clonal spread of carbapenem-resistant Acinetobacter baumannii in a neonatal intensive care unit. J Hosp Infect. 2018 Mar;98(3):300-304. doi: [10.1016/j.jhin.2017.10.015.](https://www.journalofhospitalinfection.com/article/S0195-6701(17)30581-9/abstract)

11. Maciel WG, Silva KE, **Bampi JV**, Bet GM, Ramos AC, Gales AC, Simionatto S. Identification of São Paulo metallo-beta-lactamase-1-producing Pseudomonas aeruginosa in the Central-West region of Brazil: a case study. Rev Soc Bras Med Trop. 2017 Jan-Feb;50(1):135-137. doi: [10.1590/0037-8682-0284-2016.](https://www.scielo.br/j/rsbmt/a/xbZn9N8HzZMtfNsNYGZbtnP/?format=html&lang=en)

12. Carbone Ada S, Paião DS, Sgarbi RV, Lemos EF, Cazanti RF, Ota MM, Junior AL, **Bampi JV**, Elias VP, Simionatto S, Motta-Castro AR, Pompílio MA, de Oliveira SM, Ko AI, Andrews JR, Croda J. Active and latent tuberculosis in Brazilian correctional facilities: a cross-sectional study. BMC Infect Dis. 2015 Jan 22;15:24. doi: [10.1186/s12879-015-0764-8.](https://bmcinfectdis.biomedcentral.com/articles/10.1186/s12879-015-0764-8)

## Book chapters

1.  **JOSE VICTOR BORTOLOTTO BAMPI**; FIGUEIRA, C. M.; BENTO, D. D.; ALMEIDA, L. G.. **HIV; In: Tratado de Medicina de Emergência - ABRAMEDE**, ed.1ª. : Manole, 2024, v.1, p. 1254 - 1267. ISBN: 9788520458174

2.  LEITE, O. H. M.; COSTA, A. F.; MOREIRA, A. S.; **BAMPI, J.V.B.**. **Drogas antimicobactérias não rifamicinas; In: Manual de antimicrobianos: departamento de infectologia e medicina tropical da faculdade de medicina da USP,** ed.1ª. Barueri: Manole, 2025, v.1, p. 245 - 273. ISBN: 9788520458945

3.  **JOSE VICTOR BORTOLOTTO BAMPI. Cuidado e tratamento de agravos, doenças agudas,crônicas e infecciosas em ambiente prisional; In: O itinerário de cuidado à saúde, agravos e doenças transmissíveis e não transmissíveis no âmbito da PNAISP : módulo 5**, ed. 1ª. Fiocruz Pantanal, 2026, v.1, p. 4 - 27. ISBN: 9788566909722

4.  **JOSE VICTOR BORTOLOTTO BAMPI. Cuidado em saúde na diversidade de gênero; In: O itinerário de cuidado à saúde, agravos e doenças transmissíveis e não transmissíveis no âmbito da PNAISP : módulo 5**, ed. 1ª. Fiocruz Pantanal, 2026, v.1, p. 4 - 27. ISBN: 9788566909722
